server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    types {
        text/html html;
        application/javascript js;
        text/css css;
        application/wasm wasm;
        application/octet-stream dll exe;
        image/svg+xml svg;
        font/woff2 woff2;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
